"""empty message

Revision ID: fd83d6378ab4
Revises: 
Create Date: 2021-03-29 06:54:57.840350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd83d6378ab4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('courier_type', postgresql.ENUM('foot', 'bike', 'car', name='courier_type'), nullable=True),
    sa.Column('regions', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('working_hours', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('courier_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('couriers')
    # ### end Alembic commands ###
